@startuml
class sendNotificatoin {
+ {static} void showNotification(Context,String,String,int)
+ {static} void listenForMessages(Context,String,String)
}
abstract class UserLoginActivity {
~ {abstract}void loadActivity()
~ {abstract}void changeScreen()
+ void registrationError()
+ void passwordInputError()
+ void authenticationError()
+ void onBackPressed()
}
class ExampleUnitTest {
+ void addition_isCorrect()
}
class UserLoginActivityFB {
+ void createUserWithEmailAndPassword(String,String)
+ void signInWithEmailAndPassword(String,String)
+ void addAuthStateListener()
+ void removeAuthStateListener()
}
class ChatActivity {
~ DatabaseReference chatDatabaseReference
}
abstract class UserMapActivityC {
}
class User {
+ String getUserName()
+ void setUserName(String)
+ String getPhoneNumber()
+ void setPhoneNumber(String)
+ String getUserImageUrl()
+ void setUserImageUrl(String)
+ String getRating()
+ void setRating(String)
}
class RequesterLoginActivity {
~ void loadActivity()
~ void changeScreen()
}
class RequesterMapActivityC {
+ void changeRequestButtonText(String)
}
class MapUtilities {
+ {static} int LOCATION_REQUEST_CODE
~ GoogleApiClient currentGoogleApiClient
~ SupportMapFragment mapFragment
+ GoogleApiClient getCurrentGoogleApiClient()
+ GoogleMap getmMap()
+ SupportMapFragment getMapFragment()
+ void setCurrentGoogleApiClient(GoogleApiClient)
+ void setMapFragment(SupportMapFragment)
+ void setmMap(GoogleMap)
}
class ExampleInstrumentedTest {
+ void useAppContext()
}
class UserSettingActivityC {
}
class LeaderBoardActivity {
}
class LeaderBoardActivity.HelperData {
~ String name
~ int rating
+ String toString()
+ int compareTo(HelperData)
}
class ChatAdapter {
+ ViewHolder onCreateViewHolder(ViewGroup,int)
+ void onBindViewHolder(ViewHolder,int)
+ int getItemCount()
}
class ChatAdapter.ViewHolder {
+ TextView getTextView()
}
class HelperMapActivityM {
+ void cancelJob()
+ void getAssignedRequester()
+ void LogOut()
+ void openLeaderBoard()
+ void disconnectHelper()
+ void changeHelperAvailable(Location)
+ void loadChat()
}
class UserLocation {
~ Location lastLocation
~ LocationRequest locationRequest
+ void CreateLocationRequest()
}
class RequesterMapActivityM {
~ GeoQuery geoQuery
+ void Request()
+ void LogOut()
+ void loadChat()
+ void disconnectRequester()
}
class UserLoginActivityC {
}
class HelperLoginActivity {
~ void loadActivity()
~ void changeScreen()
}
class HelperSettingsActivity {
}
class UserSettingActivityFB {
+ void saveUserInformation(String,String)
+ void getUserInfo(EditText,EditText)
+ void finishActivity()
}
class RequesterSettingsActivity {
}
class HelperMapActivityC {
}
class HelperMapActivity {
+ void ShowDialer(View)
+ Marker getJobMarker()
+ ConstraintLayout getRequesterInfo()
+ TextView getRequesterName()
+ TextView getRequesterPhone()
+ void setJobMarker(LatLng)
+ void openLeaderBoard()
+ void onLocationChanged(Location)
+ void onConnectionSuspended(int)
+ void ShowAssignedRequesterInfo(User)
+ void loadChat(String,String)
+ void ChangeUserInfo(User)
}
class MainActivity {
}
abstract class UserMapActivity {
~ UserLocation userLocation
+ void onMapReady(GoogleMap)
+ void onLocationChanged(Location)
+ void onConnected(Bundle)
+ void onRequestPermissionsResult(int,String[],int[])
+ void onConnectionSuspended(int)
+ void onConnectionFailed(ConnectionResult)
+ void ChangeScreenToMain()
+ void ChangeUserInfo(User)
+ void removeLocationUpdates()
+ Location getLastLocation()
+ {abstract}void loadChat(String,String)
+ void onBackPressed()
}
class ChatList {
+ boolean isCurrUser()
+ void setCurrUser(boolean)
+ String getMessage()
+ void setMessage(String)
}
abstract class UserMapActivityM {
~ FirebaseAuth auth
~ String userId
~ User currentUser
+ void getUserInfo()
+ void loadSetting()
+ void LogOut()
+ boolean isLoggingOut()
+ {abstract}void loadChat()
}
abstract class UserSettingActivity {
~ Uri resultUri
~ ImageView profileImage
+ void onBackPressed()
}
class RequesterMapActivity {
+ Marker getHelperMarker()
+ void setHelperMarker(LatLng)
+ void changeRequestButtonText(String)
+ void ShowAssignedHelperInfo(User)
+ void RemoveHelper()
+ void ShowDialer(View)
+ void loadChat(String,String)
}


AppCompatActivity <|-- UserLoginActivity
AppCompatActivity <|-- ChatActivity
UserLoginActivity <|-- RequesterLoginActivity
UserMapActivityC <|-- RequesterMapActivityC
AppCompatActivity <|-- LeaderBoardActivity
LeaderBoardActivity +.. LeaderBoardActivity.HelperData
Comparable <|.. LeaderBoardActivity.HelperData
Adapter <|-- ChatAdapter
ChatAdapter +.. ChatAdapter.ViewHolder
ViewHolder <|-- ChatAdapter.ViewHolder
UserMapActivityM <|-- HelperMapActivityM
UserMapActivityM <|-- RequesterMapActivityM
UserLoginActivity <|-- HelperLoginActivity
UserSettingActivity <|-- HelperSettingsActivity
UserSettingActivity <|-- RequesterSettingsActivity
UserMapActivityC <|-- HelperMapActivityC
UserMapActivity <|-- HelperMapActivity
AppCompatActivity <|-- MainActivity
LocationListener <|.. UserMapActivity
OnMapReadyCallback <|.. UserMapActivity
ConnectionCallbacks <|.. UserMapActivity
OnConnectionFailedListener <|.. UserMapActivity
LocationListener <|.. UserMapActivity
FragmentActivity <|-- UserMapActivity
AppCompatActivity <|-- UserSettingActivity
UserMapActivity <|-- RequesterMapActivity
@enduml